[package]
name = "macros_usages"
rust-version.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
my_macros = { path = "../macros" }