[package]
name = "my_macros"
rust-version.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
quote = "1.0.38"
syn = {version = "2.0.98", features = ["full"]}

[lib]
proc-macro = true

